"""Resume Kit Facade — the single in-process capability boundary for Phase 5.

Every Phase 5 transport (CLI, MCP, API, bridge) calls the capabilities in this
package instead of touching engine functions directly, so all surfaces stay in
parity and every result flows through the ``resume_kit_core`` interface
substrate.
"""

__version__ = "0.0.0"

from resume_kit_facade.alias_scope import use_alias_file
from resume_kit_facade.capabilities import (
    REGISTRY,
    add_evidence_capability,
    align_resume,
    align_terminology,
    analyze_best_practices_capability,
    analyze_shape_capability,
    ats_view_capability,
    build_base_capability,
    build_candidate_evidence_capability,
    build_perfect_capability,
    build_refine_capability,
    build_standard_capability,
    build_structure_capability,
    check_ats_structure,
    check_resume_ats,
    check_resume_job_match,
    commit_session_capability,
    compare_resume_versions,
    decide_change_capability,
    export_resume,
    extract_job_description,
    extract_resume,
    extract_resume_text_capability,
    identify_resume_gaps,
    init_project_capability,
    open_edit_session_capability,
    rank_edit_candidates_capability,
    reconcile_session_capability,
    record_edit_feedback_capability,
    refresh_preferences_capability,
    select_best_resume,
    session_prompt_capability,
    session_status_capability,
    set_active_capability,
    suggest_terminology,
    validate_faithfulness_capability,
    validate_resume_truth_capability,
)
from resume_kit_facade.models import (
    AddEvidenceRequest,
    AddEvidenceResult,
    AliasGrowthEntry,
    AlignResumeRequest,
    AlignTerminologyRequest,
    AlignTerminologyResult,
    AnalyzeBestPracticesRequest,
    AnalyzeShapeRequest,
    AtsViewRequest,
    BaseBuildResult,
    BuildBaseRequest,
    BuildCandidateEvidenceRequest,
    BuildPerfectRequest,
    BuildRefineRequest,
    BuildStandardRequest,
    BuildStructureRequest,
    CapabilityOptions,
    CheckAtsStructureRequest,
    CheckResumeAtsRequest,
    CheckResumeJobMatchRequest,
    CommitSessionRequest,
    CommitSessionResult,
    CompareResumeVersionsRequest,
    DecideChangeRequest,
    EditSessionState,
    EditSessionStatus,
    ExportResumeRequest,
    ExtractJobDescriptionRequest,
    ExtractResumeRequest,
    ExtractResumeTextRequest,
    IdentifyResumeGapsRequest,
    InitProjectRequest,
    OpenEditSessionRequest,
    RankEditCandidatesRequest,
    RankEditCandidatesResult,
    ReconcileSessionRequest,
    ReconcileSessionResult,
    RecordEditFeedbackRequest,
    RecordEditFeedbackResult,
    RefineBuildResult,
    RefreshPreferencesRequest,
    SelectBestResumeRequest,
    SessionPromptRequest,
    SessionStatusRequest,
    SetActiveRequest,
    StandardBuildResult,
    StructureBuildResult,
    SuggestTerminologyRequest,
    TerminologyAlignmentDelta,
    ValidateFaithfulnessRequest,
    ValidateResumeTruthRequest,
)
from resume_kit_facade.perfect import BuildPerfectResult, build_perfect
from resume_kit_facade.project_config import (
    ProjectConfig,
    init_project,
    load_config,
    resolve_active_resume,
    save_config,
    set_active,
    set_version,
)

__all__ = [
    # registry
    "REGISTRY",
    # capability callables
    "add_evidence_capability",
    "align_resume",
    "align_terminology",
    "analyze_best_practices_capability",
    "analyze_shape_capability",
    "ats_view_capability",
    "build_base_capability",
    "build_candidate_evidence_capability",
    "build_perfect_capability",
    "build_refine_capability",
    "build_standard_capability",
    "build_structure_capability",
    "build_perfect",
    "check_ats_structure",
    "check_resume_ats",
    "check_resume_job_match",
    "commit_session_capability",
    "compare_resume_versions",
    "decide_change_capability",
    "export_resume",
    "extract_job_description",
    "extract_resume",
    "extract_resume_text_capability",
    "identify_resume_gaps",
    "init_project_capability",
    "open_edit_session_capability",
    "rank_edit_candidates_capability",
    "record_edit_feedback_capability",
    "reconcile_session_capability",
    "refresh_preferences_capability",
    "select_best_resume",
    "session_prompt_capability",
    "session_status_capability",
    "set_active_capability",
    "suggest_terminology",
    "validate_faithfulness_capability",
    "validate_resume_truth_capability",
    # options
    "CapabilityOptions",
    # alias scoping helper
    "use_alias_file",
    # working-directory config contract
    "ProjectConfig",
    "init_project",
    "load_config",
    "resolve_active_resume",
    "save_config",
    "set_active",
    "set_version",
    # request models
    "AddEvidenceRequest",
    "AlignResumeRequest",
    "AlignTerminologyRequest",
    "AnalyzeBestPracticesRequest",
    "AnalyzeShapeRequest",
    "AtsViewRequest",
    "BuildBaseRequest",
    "BuildCandidateEvidenceRequest",
    "BuildPerfectRequest",
    "BuildRefineRequest",
    "BuildStandardRequest",
    "BuildStructureRequest",
    "CheckAtsStructureRequest",
    "CheckResumeAtsRequest",
    "CheckResumeJobMatchRequest",
    "CommitSessionRequest",
    "CompareResumeVersionsRequest",
    "DecideChangeRequest",
    "EditSessionState",
    "ExportResumeRequest",
    "ExtractJobDescriptionRequest",
    "ExtractResumeRequest",
    "ExtractResumeTextRequest",
    "IdentifyResumeGapsRequest",
    "InitProjectRequest",
    "OpenEditSessionRequest",
    "RankEditCandidatesRequest",
    "RecordEditFeedbackRequest",
    "ReconcileSessionRequest",
    "RefreshPreferencesRequest",
    "SelectBestResumeRequest",
    "SessionPromptRequest",
    "SessionStatusRequest",
    "SetActiveRequest",
    "SuggestTerminologyRequest",
    "ValidateFaithfulnessRequest",
    "ValidateResumeTruthRequest",
    # response models
    "AddEvidenceResult",
    "AliasGrowthEntry",
    "AlignTerminologyResult",
    "BaseBuildResult",
    "BuildPerfectResult",
    "CommitSessionResult",
    "RefineBuildResult",
    "StandardBuildResult",
    "StructureBuildResult",
    "EditSessionStatus",
    "RankEditCandidatesResult",
    "RecordEditFeedbackResult",
    "ReconcileSessionResult",
    "TerminologyAlignmentDelta",
]
